[book]
authors = ["Threefold Community"]
language = "en"
multilingual = false
src = "src"

[build]
create-missing = false
build-dir = "/var/www/html"

[output.html]
additional-css = ["cards.css", "thumbnails.css"]